[{
  "history_id" : "tpruig1hdym",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\n\n# to see ID and state of GPUs assigned  \npython text_to_csv_20_21.py",
  "history_output" : "Traceback (most recent call last):\n  File \"/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/text_to_csv_20_21.py\", line 20, in <module>\n    data_frame.to_csv(home+'/cmaq/cmaq_2020_2021.csv',index=False)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py\", line 3466, in to_csv\n    return DataFrameRenderer(formatter).to_csv(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/format.py\", line 1105, in to_csv\n    csv_formatter.save()\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/csvs.py\", line 237, in save\n    with get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/cmaq_2020_2021.csv'\n",
  "history_begin_time" : 1646769027892,
  "history_end_time" : 1646769094886,
  "history_notes" : null,
  "history_process" : "ennz3x",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "ca7xcju07te",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\n\n# to see ID and state of GPUs assigned  \npython text_to_csv_20_21.py",
  "history_output" : "Traceback (most recent call last):\n  File \"/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/text_to_csv_20_21.py\", line 20, in <module>\n    data_frame.to_csv(home+'/cmaq/cmaq_2020_2021.csv',index=False)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py\", line 3466, in to_csv\n    return DataFrameRenderer(formatter).to_csv(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/format.py\", line 1105, in to_csv\n    csv_formatter.save()\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/csvs.py\", line 237, in save\n    with get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/cmaq_2020_2021.csv'\n./geoweaver-l7XNL6Z2w4ZVh1BVYicuHegYj4.sh: line 21: ncl: command not found\n",
  "history_begin_time" : 1646769095477,
  "history_end_time" : 1646769155024,
  "history_notes" : null,
  "history_process" : "1wyqlm",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "zn02bqicuqu",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\n\n# to see ID and state of GPUs assigned\n  \npython preprocessing_training_data.py",
  "history_output" : "tar: /home/mislam25/l7XNL6Z2w4ZVh1BVYicuHegYj4.tar: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now\npython: can't open file '/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/preprocessing_training_data.py': [Errno 2] No such file or directory\n",
  "history_begin_time" : 1646769155379,
  "history_end_time" : 1646769212624,
  "history_notes" : null,
  "history_process" : "kyfevh",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "ax95r96eave",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\n\n# to see ID and state of GPUs assigned\n\npython training_xgboost.py",
  "history_output" : "training_xgboost\nTraceback (most recent call last):\n  File \"/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/training_xgboost.py\", line 16, in <module>\n    final=pd.read_csv(home+'/cmaq/merged_2020_2021.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/merged_2020_2021.csv'\n",
  "history_begin_time" : 1646769212711,
  "history_end_time" : 1646769337326,
  "history_notes" : null,
  "history_process" : "ykn4bh",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "eognf4a2s3w",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\n\n\npython prediction_xgboost.py",
  "history_output" : "prediction_xgboost\nTraceback (most recent call last):\n  File \"/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/prediction_xgboost.py\", line 13, in <module>\n    final=pd.read_csv(home+'/cmaq/test_2022.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/test_2022.csv'\n",
  "history_begin_time" : 1646769337512,
  "history_end_time" : 1646769381992,
  "history_notes" : null,
  "history_process" : "nlrst4",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "t6gvlclwzkm",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\ncd ~/cmaq\nmodule load ncl\n# to see ID and state of GPUs assigned\ndateYesterday=$(date -d \"3 day ago\" '+%-d')\ndateMonth=$(date -d \"yesterday\" '+%-m')\nncl dateMonth=$dateMonth dateYesterday=$dateYesterday /groups/ESS/mislam25/cmaq12_airnow_O3.ncl\n",
  "history_output" : "Traceback (most recent call last):\n  File \"/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/text_to_csv_20_21.py\", line 20, in <module>\n    data_frame.to_csv(home+'/cmaq/cmaq_2020_2021.csv',index=False)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py\", line 3466, in to_csv\n    return DataFrameRenderer(formatter).to_csv(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/format.py\", line 1105, in to_csv\n    csv_formatter.save()\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/csvs.py\", line 237, in save\n    with get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/cmaq_2020_2021.csv'\n./geoweaver-l7XNL6Z2w4ZVh1BVYicuHegYj4.sh: line 21: ncl: command not found\n",
  "history_begin_time" : 1646769095474,
  "history_end_time" : 1646769155031,
  "history_notes" : null,
  "history_process" : "3ymzeo",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "xk39ou79r2q",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\n\n# to see ID and state of GPUs assigned\ncd\npython text_to_csv_daily.py",
  "history_output" : "python: can't open file '/home/mislam25/text_to_csv_daily.py': [Errno 2] No such file or directory\n./geoweaver-l7XNL6Z2w4ZVh1BVYicuHegYj4.sh: line 20: g_data.py: command not found\n",
  "history_begin_time" : 1646769155395,
  "history_end_time" : 1646769211692,
  "history_notes" : null,
  "history_process" : "vefwgw",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "rmkasypoary",
  "history_input" : "#!/bin/bash\n#SBATCH --partition=gpuq                    # the DGX only belongs in the 'gpu'  partition\n#SBATCH --qos=gpu                           # need to select 'gpu' QoS\n#SBATCH --job-name=python-gpu\n#SBATCH --output=python-gpu.%j.out\n#SBATCH --error=python-gpu.%j.err\n#SBATCH --nodes=1\n#SBATCH --ntasks-per-node=1                 # up to 128; \n#SBATCH --gres=gpu:A100.40gb:1              # up to 8; only request what you need\n#SBATCH --mem-per-cpu=3500M                 # memory per CORE; total memory is 1 TB (1,000,000 MB)\n#SBATCH --export=ALL \n#SBATCH --time=0-00:20:00                   # set to 1hr; please choose carefully\n\nset echo\numask 0027\n\n# to see ID and state of GPUs assigned\n\npython pre_processing.py",
  "history_output" : "training_xgboost\nTraceback (most recent call last):\n  File \"/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/training_xgboost.py\", line 16, in <module>\n    final=pd.read_csv(home+'/cmaq/merged_2020_2021.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/merged_2020_2021.csv'\n",
  "history_begin_time" : 1646769212430,
  "history_end_time" : 1646769337315,
  "history_notes" : null,
  "history_process" : "gaxwis",
  "host_id" : "vneyuq",
  "indicator" : "Done"
},{
  "history_id" : "ldxw1czod2c",
  "history_input" : "#!/bin/bash\nsleep 40\n",
  "history_output" : "Traceback (most recent call last):\n  File \"/home/mislam25/gw-workspace/l7XNL6Z2w4ZVh1BVYicuHegYj4/text_to_csv_20_21.py\", line 20, in <module>\n    data_frame.to_csv(home+'/cmaq/cmaq_2020_2021.csv',index=False)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py\", line 3466, in to_csv\n    return DataFrameRenderer(formatter).to_csv(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/format.py\", line 1105, in to_csv\n    csv_formatter.save()\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/formats/csvs.py\", line 237, in save\n    with get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/cmaq_2020_2021.csv'\n",
  "history_begin_time" : 1646769027892,
  "history_end_time" : 1646769094897,
  "history_notes" : null,
  "history_process" : "zn4fot",
  "host_id" : "vneyuq",
  "indicator" : "Done"
}]
