[{
  "history_id" : "q7iztutxsaa",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/text_to_csv_2021.py",
  "history_output" : "salloc: Pending job allocation 45594\nsalloc: job 45594 queued and waiting for resources\nsalloc: job 45594 has been allocated resources\nsalloc: Granted job allocation 45594\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop067 are ready for job\nrunning_preprocess\ntext_2021\nsalloc: Relinquishing job allocation 45594\nsalloc: Job allocation 45594 has been revoked.\n",
  "history_begin_time" : 1645720348592,
  "history_end_time" : 1645720375558,
  "history_notes" : null,
  "history_process" : "ol8aa4",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "zlxhs8i69og",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/text_to_csv_2020.py",
  "history_output" : "salloc: Pending job allocation 45595\nsalloc: job 45595 queued and waiting for resources\nsalloc: job 45595 has been allocated resources\nsalloc: Granted job allocation 45595\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop068 are ready for job\nrunning_preprocess\nrunning text_2020\nsalloc: Relinquishing job allocation 45595\nsalloc: Job allocation 45595 has been revoked.\nrm: cannot remove './geoweaver-Pnc7AI1Wb1OlvyYpibun8zm73s.sh': No such file or directory\n",
  "history_begin_time" : 1645720349075,
  "history_end_time" : 1645720377500,
  "history_notes" : null,
  "history_process" : "r41da2",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "e22qxwcuyie",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/pre_processing.py",
  "history_output" : "salloc: Pending job allocation 45596\nsalloc: job 45596 queued and waiting for resources\nsalloc: job 45596 has been allocated resources\nsalloc: Granted job allocation 45596\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop067 are ready for job\nrunning_preprocess\nTraceback (most recent call last):\n  File \"/home/mislam25/cmaq/pre_processing.py\", line 74, in <module>\n    mrg_rename.drop(su.columns[[5,6]], axis = 1, inplace = True)\nNameError: name 'su' is not defined\nsalloc: Relinquishing job allocation 45596\nsalloc: Job allocation 45596 has been revoked.\n",
  "history_begin_time" : 1645720377582,
  "history_end_time" : 1645720410304,
  "history_notes" : null,
  "history_process" : "ftn2kp",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "ultcpx8fnfp",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/exploratory_data_analysis.py",
  "history_output" : "salloc: Pending job allocation 45597\nsalloc: job 45597 queued and waiting for resources\nsalloc: job 45597 has been allocated resources\nsalloc: Granted job allocation 45597\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop067 are ready for job\nrunning_preprocess\nTraceback (most recent call last):\n  File \"/home/mislam25/cmaq/exploratory_data_analysis.py\", line 34, in <module>\n    final=pd.read_csv('/home/mislam25/cmaq/merged_2020_2021.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/merged_2020_2021.csv'\nsalloc: Relinquishing job allocation 45597\nsalloc: Job allocation 45597 has been revoked.\n",
  "history_begin_time" : 1645720410783,
  "history_end_time" : 1645720466808,
  "history_notes" : null,
  "history_process" : "wfd3c5",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "ffgmyz2gc6f",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/training_xgboost.py",
  "history_output" : "salloc: Pending job allocation 45598\nsalloc: job 45598 queued and waiting for resources\nsalloc: job 45598 has been allocated resources\nsalloc: Granted job allocation 45598\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop067 are ready for job\nrunning xgboost_training\nTraceback (most recent call last):\n  File \"/home/mislam25/cmaq/training_xgboost.py\", line 12, in <module>\n    final=pd.read_csv('/home/mislam25/cmaq/merged_2020_2021.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/merged_2020_2021.csv'\nsalloc: Relinquishing job allocation 45598\nsalloc: Job allocation 45598 has been revoked.\n./geoweaver-Pnc7AI1Wb1OlvyYpibun8zm73s.sh: line 4: .py: command not found\nrm: cannot remove './geoweaver-Pnc7AI1Wb1OlvyYpibun8zm73s.sh': No such file or directory\n",
  "history_begin_time" : 1645720467826,
  "history_end_time" : 1645720525131,
  "history_notes" : null,
  "history_process" : "j7uo3v",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "r2lg0wq9pqq",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/prediction_xgboost.py",
  "history_output" : "salloc: Pending job allocation 45601\nsalloc: job 45601 queued and waiting for resources\nsalloc: job 45601 has been allocated resources\nsalloc: Granted job allocation 45601\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop067 are ready for job\nrunning prediction xgboost\nTraceback (most recent call last):\n  File \"/home/mislam25/cmaq/prediction_xgboost.py\", line 8, in <module>\n    final=pd.read_csv('/home/mislam25/cmaq/merged_2020_2021.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/merged_2020_2021.csv'\nsalloc: Relinquishing job allocation 45601\nsalloc: Job allocation 45601 has been revoked.\n",
  "history_begin_time" : 1645720525829,
  "history_end_time" : 1645720550936,
  "history_notes" : null,
  "history_process" : "zt10an",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "7uzyw5dt4rr",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/training_random_forest.py",
  "history_output" : "bash: ./geoweaver-Pnc7AI1Wb1OlvyYpibun8zm73s.sh: /bin/bash: bad interpreter: Text file busy\n",
  "history_begin_time" : 1645720467479,
  "history_end_time" : 1645720476577,
  "history_notes" : null,
  "history_process" : "48iyth",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "rkroeinrotu",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/prediction_random_forest.py",
  "history_output" : "salloc: Pending job allocation 45599\nsalloc: job 45599 queued and waiting for resources\nsalloc: job 45599 has been allocated resources\nsalloc: Granted job allocation 45599\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop068 are ready for job\nrunning prediciton rf\nTraceback (most recent call last):\n  File \"/home/mislam25/cmaq/prediction_random_forest.py\", line 8, in <module>\n    final=pd.read_csv('/home/mislam25/cmaq/merged_2020_2021.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/merged_2020_2021.csv'\nsalloc: Relinquishing job allocation 45599\nsalloc: Job allocation 45599 has been revoked.\n",
  "history_begin_time" : 1645720476893,
  "history_end_time" : 1645720499554,
  "history_notes" : null,
  "history_process" : "bembwt",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "gwxhiw0sw2e",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/training_autokeras.py",
  "history_output" : "/bin/bash: ./geoweaver-Pnc7AI1Wb1OlvyYpibun8zm73s.sh: No such file or directory\nrm: cannot remove './geoweaver-Pnc7AI1Wb1OlvyYpibun8zm73s.sh': No such file or directory\n",
  "history_begin_time" : 1645720467462,
  "history_end_time" : 1645720476594,
  "history_notes" : null,
  "history_process" : "l0t844",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "9y0h5wwodeo",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/prediction_autokeras.py",
  "history_output" : "salloc: Pending job allocation 45600\nsalloc: job 45600 queued and waiting for resources\nsalloc: job 45600 has been allocated resources\nsalloc: Granted job allocation 45600\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop068 are ready for job\nrunning predicion autokeras\n2022-02-24 11:35:00.722996: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ohpc/pub/libs/hwloc/2.1.0/lib:/opt/ohpc/pub/mpi/libfabric/1.10.1/lib:/opt/ohpc/pub/mpi/ucx-ohpc/1.8.0/lib:/opt/ohpc/pub/mpi/openmpi4-gnu9/4.0.4/lib:/opt/ohpc/pub/compiler/gcc/9.3.0/lib64:/lib64\n2022-02-24 11:35:00.723020: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\nTraceback (most recent call last):\n  File \"/home/mislam25/cmaq/prediction_autokeras.py\", line 20, in <module>\n    final=pd.read_csv('/home/mislam25/cmaq/merged_2020_2021.csv')\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py\", line 311, in wrapper\n    return func(*args, **kwargs)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 586, in read_csv\n    return _read(filepath_or_buffer, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 482, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 811, in __init__\n    self._engine = self._make_engine(self.engine)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py\", line 1040, in _make_engine\n    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py\", line 51, in __init__\n    self._open_handles(src, kwds)\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py\", line 222, in _open_handles\n    self.handles = get_handle(\n  File \"/home/mislam25/anaconda3/lib/python3.9/site-packages/pandas/io/common.py\", line 702, in get_handle\n    handle = open(\nFileNotFoundError: [Errno 2] No such file or directory: '/home/mislam25/cmaq/merged_2020_2021.csv'\nsalloc: Relinquishing job allocation 45600\nsalloc: Job allocation 45600 has been revoked.\nrm: cannot remove './geoweaver-Pnc7AI1Wb1OlvyYpibun8zm73s.sh': No such file or directory\n",
  "history_begin_time" : 1645720477599,
  "history_end_time" : 1645720674833,
  "history_notes" : null,
  "history_process" : "zmy3vb",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
},{
  "history_id" : "3krewj5uojz",
  "history_input" : "#!/bin/bash\n#write your bash script\nsalloc -p normal  -n 1  --cpus-per-task=12 --mem=15GB -t 0-00:05:00 python cmaq/model_comparison.py",
  "history_output" : "salloc: Pending job allocation 45602\nsalloc: job 45602 queued and waiting for resources\nsalloc: job 45602 has been allocated resources\nsalloc: Granted job allocation 45602\nsalloc: Waiting for resource configuration\nsalloc: Nodes hop067 are ready for job\n[]\nsalloc: Relinquishing job allocation 45602\nsalloc: Job allocation 45602 has been revoked.\n",
  "history_begin_time" : 1645720675494,
  "history_end_time" : 1645720727562,
  "history_notes" : null,
  "history_process" : "z1t6b2",
  "host_id" : "w6jk5o",
  "indicator" : "Done"
}]
